package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/* JADX INFO: loaded from: classes.dex */
class RegionDefaults {
    public static List<Region> getRegions() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("af-south-1", "TryRoom");
        arrayList.add(region);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region, "kms", "TryRoom", false, true);
        updateRegion(region, "lambda", "TryRoom", false, true);
        updateRegion(region, "logs", "TryRoom", false, true);
        updateRegion(region, "s3", "TryRoom", false, true);
        updateRegion(region, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region2 = new Region("ap-northeast-1", "TryRoom");
        arrayList.add(region2);
        updateRegion(region2, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region2, "cognito-identity", "TryRoom", false, true);
        updateRegion(region2, "cognito-idp", "TryRoom", false, true);
        updateRegion(region2, "cognito-sync", "TryRoom", false, true);
        updateRegion(region2, "data.iot", "TryRoom", false, true);
        updateRegion(region2, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region2, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region2, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region2, "firehose", "TryRoom", false, true);
        updateRegion(region2, "iot", "TryRoom", false, true);
        updateRegion(region2, "kinesis", "TryRoom", false, true);
        updateRegion(region2, "kms", "TryRoom", false, true);
        updateRegion(region2, "lambda", "TryRoom", false, true);
        updateRegion(region2, "logs", "TryRoom", false, true);
        updateRegion(region2, "polly", "TryRoom", false, true);
        updateRegion(region2, "s3", "TryRoom", false, true);
        updateRegion(region2, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region2, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region2, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region2, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region3 = new Region("ap-northeast-2", "TryRoom");
        arrayList.add(region3);
        updateRegion(region3, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region3, "cognito-identity", "TryRoom", false, true);
        updateRegion(region3, "cognito-idp", "TryRoom", false, true);
        updateRegion(region3, "cognito-sync", "TryRoom", false, true);
        updateRegion(region3, "data.iot", "TryRoom", false, true);
        updateRegion(region3, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region3, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region3, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region3, "iot", "TryRoom", false, true);
        updateRegion(region3, "kinesis", "TryRoom", false, true);
        updateRegion(region3, "kms", "TryRoom", false, true);
        updateRegion(region3, "lambda", "TryRoom", false, true);
        updateRegion(region3, "logs", "TryRoom", false, true);
        updateRegion(region3, "polly", "TryRoom", false, true);
        updateRegion(region3, "s3", "TryRoom", false, true);
        updateRegion(region3, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region3, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region3, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region4 = new Region("ap-south-1", "TryRoom");
        arrayList.add(region4);
        updateRegion(region4, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region4, "cognito-identity", "TryRoom", false, true);
        updateRegion(region4, "cognito-idp", "TryRoom", false, true);
        updateRegion(region4, "cognito-sync", "TryRoom", false, true);
        updateRegion(region4, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region4, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region4, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region4, "kinesis", "TryRoom", false, true);
        updateRegion(region4, "kms", "TryRoom", false, true);
        updateRegion(region4, "lambda", "TryRoom", false, true);
        updateRegion(region4, "logs", "TryRoom", false, true);
        updateRegion(region4, "polly", "TryRoom", false, true);
        updateRegion(region4, "s3", "TryRoom", false, true);
        updateRegion(region4, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region4, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region4, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region5 = new Region("ap-southeast-1", "TryRoom");
        arrayList.add(region5);
        updateRegion(region5, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region5, "cognito-identity", "TryRoom", false, true);
        updateRegion(region5, "cognito-idp", "TryRoom", false, true);
        updateRegion(region5, "cognito-sync", "TryRoom", false, true);
        updateRegion(region5, "data.iot", "TryRoom", false, true);
        updateRegion(region5, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region5, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region5, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region5, "iot", "TryRoom", false, true);
        updateRegion(region5, "kinesis", "TryRoom", false, true);
        updateRegion(region5, "kms", "TryRoom", false, true);
        updateRegion(region5, "lambda", "TryRoom", false, true);
        updateRegion(region5, "logs", "TryRoom", false, true);
        updateRegion(region5, "polly", "TryRoom", false, true);
        updateRegion(region5, "s3", "TryRoom", false, true);
        updateRegion(region5, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region5, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region5, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region5, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region6 = new Region("ap-southeast-2", "TryRoom");
        arrayList.add(region6);
        updateRegion(region6, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region6, "cognito-identity", "TryRoom", false, true);
        updateRegion(region6, "cognito-idp", "TryRoom", false, true);
        updateRegion(region6, "cognito-sync", "TryRoom", false, true);
        updateRegion(region6, "data.iot", "TryRoom", false, true);
        updateRegion(region6, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region6, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region6, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region6, "iot", "TryRoom", false, true);
        updateRegion(region6, "kinesis", "TryRoom", false, true);
        updateRegion(region6, "kms", "TryRoom", false, true);
        updateRegion(region6, "lambda", "TryRoom", false, true);
        updateRegion(region6, "logs", "TryRoom", false, true);
        updateRegion(region6, "polly", "TryRoom", false, true);
        updateRegion(region6, "s3", "TryRoom", false, true);
        updateRegion(region6, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region6, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region6, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region6, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region7 = new Region("ca-central-1", "TryRoom");
        arrayList.add(region7);
        updateRegion(region7, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region7, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region7, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region7, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region7, "kinesis", "TryRoom", false, true);
        updateRegion(region7, "kms", "TryRoom", false, true);
        updateRegion(region7, "lambda", "TryRoom", false, true);
        updateRegion(region7, "logs", "TryRoom", false, true);
        updateRegion(region7, "polly", "TryRoom", false, true);
        updateRegion(region7, "s3", "TryRoom", false, true);
        updateRegion(region7, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region7, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region7, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region8 = new Region("eu-central-1", "TryRoom");
        arrayList.add(region8);
        updateRegion(region8, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region8, "cognito-identity", "TryRoom", false, true);
        updateRegion(region8, "cognito-idp", "TryRoom", false, true);
        updateRegion(region8, "cognito-sync", "TryRoom", false, true);
        updateRegion(region8, "data.iot", "TryRoom", false, true);
        updateRegion(region8, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region8, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region8, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region8, "firehose", "TryRoom", false, true);
        updateRegion(region8, "iot", "TryRoom", false, true);
        updateRegion(region8, "kinesis", "TryRoom", false, true);
        updateRegion(region8, "kms", "TryRoom", false, true);
        updateRegion(region8, "lambda", "TryRoom", false, true);
        updateRegion(region8, "logs", "TryRoom", false, true);
        updateRegion(region8, "polly", "TryRoom", false, true);
        updateRegion(region8, "s3", "TryRoom", false, true);
        updateRegion(region8, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region8, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region8, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region9 = new Region("eu-central-2", "TryRoom");
        arrayList.add(region9);
        updateRegion(region9, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region9, "cognito-identity", "TryRoom", false, true);
        updateRegion(region9, "cognito-idp", "TryRoom", false, true);
        updateRegion(region9, "cognito-sync", "TryRoom", false, true);
        updateRegion(region9, "data.iot", "TryRoom", false, true);
        updateRegion(region9, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region9, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region9, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region9, "firehose", "TryRoom", false, true);
        updateRegion(region9, "iot", "TryRoom", false, true);
        updateRegion(region9, "kinesis", "TryRoom", false, true);
        updateRegion(region9, "kms", "TryRoom", false, true);
        updateRegion(region9, "lambda", "TryRoom", false, true);
        updateRegion(region9, "logs", "TryRoom", false, true);
        updateRegion(region9, "polly", "TryRoom", false, true);
        updateRegion(region9, "s3", "TryRoom", false, true);
        updateRegion(region9, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region9, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region9, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region9, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region10 = new Region("eu-south-1", "TryRoom");
        arrayList.add(region10);
        updateRegion(region10, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region10, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region10, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region10, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region10, "lambda", "TryRoom", false, true);
        updateRegion(region10, "logs", "TryRoom", false, true);
        updateRegion(region10, "s3", "TryRoom", false, true);
        updateRegion(region10, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region10, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region10, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region11 = new Region("eu-south-2", "TryRoom");
        arrayList.add(region11);
        updateRegion(region11, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region11, "cognito-identity", "TryRoom", false, true);
        updateRegion(region11, "cognito-idp", "TryRoom", false, true);
        updateRegion(region11, "cognito-sync", "TryRoom", false, true);
        updateRegion(region11, "data.iot", "TryRoom", false, true);
        updateRegion(region11, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region11, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region11, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region11, "firehose", "TryRoom", false, true);
        updateRegion(region11, "iot", "TryRoom", false, true);
        updateRegion(region11, "kinesis", "TryRoom", false, true);
        updateRegion(region11, "kms", "TryRoom", false, true);
        updateRegion(region11, "lambda", "TryRoom", false, true);
        updateRegion(region11, "logs", "TryRoom", false, true);
        updateRegion(region11, "polly", "TryRoom", false, true);
        updateRegion(region11, "s3", "TryRoom", false, true);
        updateRegion(region11, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region11, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region11, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region11, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region12 = new Region("eu-west-1", "TryRoom");
        arrayList.add(region12);
        updateRegion(region12, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region12, "cognito-identity", "TryRoom", false, true);
        updateRegion(region12, "cognito-idp", "TryRoom", false, true);
        updateRegion(region12, "cognito-sync", "TryRoom", false, true);
        updateRegion(region12, "data.iot", "TryRoom", false, true);
        updateRegion(region12, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region12, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region12, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region12, "email", "TryRoom", false, true);
        updateRegion(region12, "firehose", "TryRoom", false, true);
        updateRegion(region12, "iot", "TryRoom", false, true);
        updateRegion(region12, "kinesis", "TryRoom", false, true);
        updateRegion(region12, "kms", "TryRoom", false, true);
        updateRegion(region12, "lambda", "TryRoom", false, true);
        updateRegion(region12, "logs", "TryRoom", false, true);
        updateRegion(region12, "machinelearning", "TryRoom", false, true);
        updateRegion(region12, "polly", "TryRoom", false, true);
        updateRegion(region12, "rekognition", "TryRoom", false, true);
        updateRegion(region12, "s3", "TryRoom", false, true);
        updateRegion(region12, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region12, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region12, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region12, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region13 = new Region("eu-west-2", "TryRoom");
        arrayList.add(region13);
        updateRegion(region13, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region13, "cognito-identity", "TryRoom", false, true);
        updateRegion(region13, "cognito-idp", "TryRoom", false, true);
        updateRegion(region13, "cognito-sync", "TryRoom", false, true);
        updateRegion(region13, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region13, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region13, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region13, "iot", "TryRoom", false, true);
        updateRegion(region13, "kinesis", "TryRoom", false, true);
        updateRegion(region13, "kms", "TryRoom", false, true);
        updateRegion(region13, "lambda", "TryRoom", false, true);
        updateRegion(region13, "logs", "TryRoom", false, true);
        updateRegion(region13, "polly", "TryRoom", false, true);
        updateRegion(region13, "s3", "TryRoom", false, true);
        updateRegion(region13, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region13, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region13, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region14 = new Region("eu-west-3", "TryRoom");
        arrayList.add(region14);
        updateRegion(region14, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region14, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region14, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region14, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region14, "kinesis", "TryRoom", false, true);
        updateRegion(region14, "kms", "TryRoom", false, true);
        updateRegion(region14, "lambda", "TryRoom", false, true);
        updateRegion(region14, "logs", "TryRoom", false, true);
        updateRegion(region14, "polly", "TryRoom", false, true);
        updateRegion(region14, "s3", "TryRoom", false, true);
        updateRegion(region14, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region14, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region14, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region15 = new Region("sa-east-1", "TryRoom");
        arrayList.add(region15);
        updateRegion(region15, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region15, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region15, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region15, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region15, "kinesis", "TryRoom", false, true);
        updateRegion(region15, "kms", "TryRoom", false, true);
        updateRegion(region15, "lambda", "TryRoom", false, true);
        updateRegion(region15, "logs", "TryRoom", false, true);
        updateRegion(region15, "polly", "TryRoom", false, true);
        updateRegion(region15, "s3", "TryRoom", false, true);
        updateRegion(region15, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region15, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region15, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region15, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region16 = new Region("us-east-1", "TryRoom");
        arrayList.add(region16);
        updateRegion(region16, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region16, "cognito-identity", "TryRoom", false, true);
        updateRegion(region16, "cognito-idp", "TryRoom", false, true);
        updateRegion(region16, "cognito-sync", "TryRoom", false, true);
        updateRegion(region16, "data.iot", "TryRoom", false, true);
        updateRegion(region16, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region16, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region16, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region16, "email", "TryRoom", false, true);
        updateRegion(region16, "firehose", "TryRoom", false, true);
        updateRegion(region16, "iot", "TryRoom", false, true);
        updateRegion(region16, "kinesis", "TryRoom", false, true);
        updateRegion(region16, "kms", "TryRoom", false, true);
        updateRegion(region16, "lambda", "TryRoom", false, true);
        updateRegion(region16, "logs", "TryRoom", false, true);
        updateRegion(region16, "machinelearning", "TryRoom", false, true);
        updateRegion(region16, "mobileanalytics", "TryRoom", false, true);
        updateRegion(region16, "pinpoint", "TryRoom", false, true);
        updateRegion(region16, "polly", "TryRoom", false, true);
        updateRegion(region16, "rekognition", "TryRoom", false, true);
        updateRegion(region16, "s3", "TryRoom", false, true);
        updateRegion(region16, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region16, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region16, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region16, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region17 = new Region("us-east-2", "TryRoom");
        arrayList.add(region17);
        updateRegion(region17, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region17, "cognito-identity", "TryRoom", false, true);
        updateRegion(region17, "cognito-idp", "TryRoom", false, true);
        updateRegion(region17, "cognito-sync", "TryRoom", false, true);
        updateRegion(region17, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region17, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region17, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region17, "firehose", "TryRoom", false, true);
        updateRegion(region17, "iot", "TryRoom", false, true);
        updateRegion(region17, "kinesis", "TryRoom", false, true);
        updateRegion(region17, "kms", "TryRoom", false, true);
        updateRegion(region17, "lambda", "TryRoom", false, true);
        updateRegion(region17, "logs", "TryRoom", false, true);
        updateRegion(region17, "polly", "TryRoom", false, true);
        updateRegion(region17, "s3", "TryRoom", false, true);
        updateRegion(region17, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region17, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region17, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region18 = new Region("us-west-1", "TryRoom");
        arrayList.add(region18);
        updateRegion(region18, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region18, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region18, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region18, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region18, "kinesis", "TryRoom", false, true);
        updateRegion(region18, "kms", "TryRoom", false, true);
        updateRegion(region18, "lambda", "TryRoom", false, true);
        updateRegion(region18, "logs", "TryRoom", false, true);
        updateRegion(region18, "polly", "TryRoom", false, true);
        updateRegion(region18, "s3", "TryRoom", false, true);
        updateRegion(region18, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region18, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region18, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region18, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region19 = new Region("us-west-2", "TryRoom");
        arrayList.add(region19);
        updateRegion(region19, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region19, "cognito-identity", "TryRoom", false, true);
        updateRegion(region19, "cognito-idp", "TryRoom", false, true);
        updateRegion(region19, "cognito-sync", "TryRoom", false, true);
        updateRegion(region19, "data.iot", "TryRoom", false, true);
        updateRegion(region19, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region19, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region19, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region19, "email", "TryRoom", false, true);
        updateRegion(region19, "firehose", "TryRoom", false, true);
        updateRegion(region19, "iot", "TryRoom", false, true);
        updateRegion(region19, "kinesis", "TryRoom", false, true);
        updateRegion(region19, "kms", "TryRoom", false, true);
        updateRegion(region19, "lambda", "TryRoom", false, true);
        updateRegion(region19, "logs", "TryRoom", false, true);
        updateRegion(region19, "polly", "TryRoom", false, true);
        updateRegion(region19, "rekognition", "TryRoom", false, true);
        updateRegion(region19, "s3", "TryRoom", false, true);
        updateRegion(region19, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region19, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region19, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region19, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region20 = new Region("cn-north-1", "TryRoom");
        arrayList.add(region20);
        updateRegion(region20, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region20, "cognito-identity", "TryRoom", false, true);
        updateRegion(region20, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region20, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region20, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region20, "iot", "TryRoom", false, true);
        updateRegion(region20, "kinesis", "TryRoom", false, true);
        updateRegion(region20, "lambda", "TryRoom", false, true);
        updateRegion(region20, "logs", "TryRoom", false, true);
        updateRegion(region20, "s3", "TryRoom", false, true);
        updateRegion(region20, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region20, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region20, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region21 = new Region("cn-northwest-1", "TryRoom");
        arrayList.add(region21);
        updateRegion(region21, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region21, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region21, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region21, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region21, "kinesis", "TryRoom", false, true);
        updateRegion(region21, "logs", "TryRoom", false, true);
        updateRegion(region21, "s3", "TryRoom", false, true);
        updateRegion(region21, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region21, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region21, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region22 = new Region("us-gov-west-1", "TryRoom");
        arrayList.add(region22);
        updateRegion(region22, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region22, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region22, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region22, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region22, "kinesis", "TryRoom", false, true);
        updateRegion(region22, "kms", "TryRoom", false, true);
        updateRegion(region22, "lambda", "TryRoom", false, true);
        updateRegion(region22, "logs", "TryRoom", false, true);
        updateRegion(region22, "rekognition", "TryRoom", false, true);
        updateRegion(region22, "s3", "TryRoom", false, true);
        updateRegion(region22, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region22, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region22, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region23 = new Region("eu-north-1", "TryRoom");
        arrayList.add(region23);
        updateRegion(region23, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region23, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region23, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region23, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region23, "firehose", "TryRoom", false, true);
        updateRegion(region23, "iot", "TryRoom", false, true);
        updateRegion(region23, "kinesis", "TryRoom", false, true);
        updateRegion(region23, "kms", "TryRoom", false, true);
        updateRegion(region23, "lambda", "TryRoom", false, true);
        updateRegion(region23, "logs", "TryRoom", false, true);
        updateRegion(region23, "s3", "TryRoom", false, true);
        updateRegion(region23, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region23, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region23, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region24 = new Region("ap-east-1", "TryRoom");
        arrayList.add(region24);
        updateRegion(region24, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region24, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region24, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region24, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region24, "firehose", "TryRoom", false, true);
        updateRegion(region24, "kinesis", "TryRoom", false, true);
        updateRegion(region24, "kms", "TryRoom", false, true);
        updateRegion(region24, "lambda", "TryRoom", false, true);
        updateRegion(region24, "logs", "TryRoom", false, true);
        updateRegion(region24, "polly", "TryRoom", false, true);
        updateRegion(region24, "s3", "TryRoom", false, true);
        updateRegion(region24, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region24, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region24, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region25 = new Region("me-south-1", "TryRoom");
        arrayList.add(region25);
        updateRegion(region25, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region25, "cognito-identity", "TryRoom", false, true);
        updateRegion(region25, "cognito-idp", "TryRoom", false, true);
        updateRegion(region25, "cognito-sync", "TryRoom", false, true);
        updateRegion(region25, "data.iot", "TryRoom", false, true);
        updateRegion(region25, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region25, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region25, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region25, "firehose", "TryRoom", false, true);
        updateRegion(region25, "iot", "TryRoom", false, true);
        updateRegion(region25, "kinesis", "TryRoom", false, true);
        updateRegion(region25, "kms", "TryRoom", false, true);
        updateRegion(region25, "lambda", "TryRoom", false, true);
        updateRegion(region25, "logs", "TryRoom", false, true);
        updateRegion(region25, "polly", "TryRoom", false, true);
        updateRegion(region25, "s3", "TryRoom", false, true);
        updateRegion(region25, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region25, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region25, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region25, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region26 = new Region("ap-southeast-3", "TryRoom");
        arrayList.add(region26);
        updateRegion(region26, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region26, "cognito-identity", "TryRoom", false, true);
        updateRegion(region26, "cognito-idp", "TryRoom", false, true);
        updateRegion(region26, "cognito-sync", "TryRoom", false, true);
        updateRegion(region26, "data.iot", "TryRoom", false, true);
        updateRegion(region26, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region26, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region26, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region26, "firehose", "TryRoom", false, true);
        updateRegion(region26, "iot", "TryRoom", false, true);
        updateRegion(region26, "kinesis", "TryRoom", false, true);
        updateRegion(region26, "kms", "TryRoom", false, true);
        updateRegion(region26, "lambda", "TryRoom", false, true);
        updateRegion(region26, "logs", "TryRoom", false, true);
        updateRegion(region26, "polly", "TryRoom", false, true);
        updateRegion(region26, "s3", "TryRoom", false, true);
        updateRegion(region26, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region26, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region26, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region26, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region27 = new Region("me-central-1", "TryRoom");
        arrayList.add(region27);
        updateRegion(region27, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region27, "cognito-identity", "TryRoom", false, true);
        updateRegion(region27, "cognito-idp", "TryRoom", false, true);
        updateRegion(region27, "cognito-sync", "TryRoom", false, true);
        updateRegion(region27, "data.iot", "TryRoom", false, true);
        updateRegion(region27, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region27, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region27, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region27, "firehose", "TryRoom", false, true);
        updateRegion(region27, "iot", "TryRoom", false, true);
        updateRegion(region27, "kinesis", "TryRoom", false, true);
        updateRegion(region27, "kms", "TryRoom", false, true);
        updateRegion(region27, "lambda", "TryRoom", false, true);
        updateRegion(region27, "logs", "TryRoom", false, true);
        updateRegion(region27, "polly", "TryRoom", false, true);
        updateRegion(region27, "s3", "TryRoom", false, true);
        updateRegion(region27, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region27, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region27, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region27, ServiceAbbreviations.STS, "TryRoom", false, true);
        Region region28 = new Region("ap-south-2", "TryRoom");
        arrayList.add(region28);
        updateRegion(region28, ServiceAbbreviations.Autoscaling, "TryRoom", false, true);
        updateRegion(region28, "cognito-identity", "TryRoom", false, true);
        updateRegion(region28, "cognito-idp", "TryRoom", false, true);
        updateRegion(region28, "cognito-sync", "TryRoom", false, true);
        updateRegion(region28, "data.iot", "TryRoom", false, true);
        updateRegion(region28, ServiceAbbreviations.Dynamodb, "TryRoom", false, true);
        updateRegion(region28, ServiceAbbreviations.EC2, "TryRoom", false, true);
        updateRegion(region28, ServiceAbbreviations.ElasticLoadbalancing, "TryRoom", false, true);
        updateRegion(region28, "firehose", "TryRoom", false, true);
        updateRegion(region28, "iot", "TryRoom", false, true);
        updateRegion(region28, "kinesis", "TryRoom", false, true);
        updateRegion(region28, "kms", "TryRoom", false, true);
        updateRegion(region28, "lambda", "TryRoom", false, true);
        updateRegion(region28, "logs", "TryRoom", false, true);
        updateRegion(region28, "polly", "TryRoom", false, true);
        updateRegion(region28, "s3", "TryRoom", false, true);
        updateRegion(region28, ServiceAbbreviations.SimpleDB, "TryRoom", false, true);
        updateRegion(region28, ServiceAbbreviations.SNS, "TryRoom", false, true);
        updateRegion(region28, ServiceAbbreviations.SQS, "TryRoom", false, true);
        updateRegion(region28, ServiceAbbreviations.STS, "TryRoom", false, true);
        return arrayList;
    }

    private static void updateRegion(Region region, String str, String str2, boolean z9, boolean z10) {
        Map<String, String> serviceEndpoints = region.getServiceEndpoints();
        Map<String, Boolean> httpSupport = region.getHttpSupport();
        Map<String, Boolean> httpsSupport = region.getHttpsSupport();
        serviceEndpoints.put(str, str2);
        httpSupport.put(str, Boolean.valueOf(z9));
        httpsSupport.put(str, Boolean.valueOf(z10));
    }
}
